# Generated by Django 3.2.6 on 2021-08-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExitTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ocupacao', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('EST', 'Estudante')], max_length=3)),
                ('feedback', models.TextField()),
                ('data', models.DateField()),
                ('nota', models.PositiveIntegerField(default=0)),
                ('duvidas', models.CharField(choices=[('PY', 'PYTHON'), ('HTML', 'HTML'), ('CSS', 'CSS')], max_length=6)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
